[package]
name = "findutils"
version = "0.1.0"
authors = ["mcharsley <mcharsley@google.com>"]
edition = "2018"

[dependencies]
glob = "0.3"
walkdir = "2.3"
tempdir = "0.3"
regex = "1.4"

[[bin]]
name = "find"
path = "src/find/main.rs"

[[bin]]
name = "testing-commandline"
path = "src/testing/commandline/main.rs"
